import requests

assessments = [
    {
        "squad_id": 1,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 4},
            {"question_id": 2, "value": 1},
            {"question_id": 3, "value": 0},
            {"question_id": 4, "value": 3},
            {"question_id": 5, "value": 5},
            {"question_id": 6, "value": 2},
            {"question_id": 7, "value": 1},
            {"question_id": 8, "value": 4},
            {"question_id": 9, "value": 0},
            {"question_id": 10, "value": 3},
        ],
    },
    {
        "squad_id": 2,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 2},
            {"question_id": 2, "value": 5},
            {"question_id": 3, "value": 3},
            {"question_id": 4, "value": 4},
            {"question_id": 5, "value": 1},
            {"question_id": 6, "value": 0},
            {"question_id": 7, "value": 4},
            {"question_id": 8, "value": 2},
            {"question_id": 9, "value": 5},
            {"question_id": 10, "value": 1},
        ],
    },
    {
        "squad_id": 3,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 0},
            {"question_id": 2, "value": 2},
            {"question_id": 3, "value": 5},
            {"question_id": 4, "value": 3},
            {"question_id": 5, "value": 4},
            {"question_id": 6, "value": 1},
            {"question_id": 7, "value": 0},
            {"question_id": 8, "value": 2},
            {"question_id": 9, "value": 3},
            {"question_id": 10, "value": 5},
        ],
    },
    {
        "squad_id": 4,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 5},
            {"question_id": 2, "value": 3},
            {"question_id": 3, "value": 2},
            {"question_id": 4, "value": 1},
            {"question_id": 5, "value": 0},
            {"question_id": 6, "value": 4},
            {"question_id": 7, "value": 3},
            {"question_id": 8, "value": 5},
            {"question_id": 9, "value": 1},
            {"question_id": 10, "value": 2},
        ],
    },
    {
        "squad_id": 5,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 1},
            {"question_id": 2, "value": 4},
            {"question_id": 3, "value": 0},
            {"question_id": 4, "value": 2},
            {"question_id": 5, "value": 3},
            {"question_id": 6, "value": 5},
            {"question_id": 7, "value": 2},
            {"question_id": 8, "value": 1},
            {"question_id": 9, "value": 4},
            {"question_id": 10, "value": 5},
        ],
    },
    {
        "squad_id": 6,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 3},
            {"question_id": 2, "value": 0},
            {"question_id": 3, "value": 4},
            {"question_id": 4, "value": 5},
            {"question_id": 5, "value": 2},
            {"question_id": 6, "value": 3},
            {"question_id": 7, "value": 1},
            {"question_id": 8, "value": 0},
            {"question_id": 9, "value": 2},
            {"question_id": 10, "value": 4},
        ],
    },
    {
        "squad_id": 7,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 4},
            {"question_id": 2, "value": 2},
            {"question_id": 3, "value": 1},
            {"question_id": 4, "value": 0},
            {"question_id": 5, "value": 5},
            {"question_id": 6, "value": 1},
            {"question_id": 7, "value": 0},
            {"question_id": 8, "value": 3},
            {"question_id": 9, "value": 2},
            {"question_id": 10, "value": 5},
        ],
    },
    {
        "squad_id": 8,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 5},
            {"question_id": 2, "value": 4},
            {"question_id": 3, "value": 3},
            {"question_id": 4, "value": 2},
            {"question_id": 5, "value": 1},
            {"question_id": 6, "value": 0},
            {"question_id": 7, "value": 4},
            {"question_id": 8, "value": 1},
            {"question_id": 9, "value": 5},
            {"question_id": 10, "value": 3},
        ],
    },
    {
        "squad_id": 9,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 2},
            {"question_id": 2, "value": 5},
            {"question_id": 3, "value": 1},
            {"question_id": 4, "value": 4},
            {"question_id": 5, "value": 0},
            {"question_id": 6, "value": 3},
            {"question_id": 7, "value": 2},
            {"question_id": 8, "value": 1},
            {"question_id": 9, "value": 4},
            {"question_id": 10, "value": 5},
        ],
    },
    {
        "squad_id": 10,
        "assessment_cyle": "02-2025",
        "answers": [
            {"question_id": 1, "value": 0},
            {"question_id": 2, "value": 3},
            {"question_id": 3, "value": 5},
            {"question_id": 4, "value": 1},
            {"question_id": 5, "value": 2},
            {"question_id": 6, "value": 4},
            {"question_id": 7, "value": 3},
            {"question_id": 8, "value": 0},
            {"question_id": 9, "value": 2},
        ],
    },
]

for assessment in assessments:
    response = requests.post("http://localhost:8000/assessments", headers={"Content-Type": "application/json"}, json=assessment)
    print(response.status_code)
